baseURL = "https://beccalynch.com"
languageCode = "en-us"
title = "Becca Lynch"
theme = "researcher"
enableEmoji = true

[params]
  favicon = "favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  "/" = "/:filename"

[[menu.main]]
  name = "Resume"
  url = "/resume"
  weight = 1

